/**
 * Markdown output — formatted report for docs/PRs.
 */

import type { ScanResult, Finding } from "../../core/finding.js";
import { Severity } from "../../core/finding.js";

const SEVERITY_EMOJI: Record<Severity, string> = {
  [Severity.Critical]: "🔴",
  [Severity.High]: "🟠",
  [Severity.Medium]: "🟡",
  [Severity.Low]: "🔵",
  [Severity.Info]: "⚪",
};

export function renderMarkdown(result: ScanResult): string {
  const lines: string[] = [];

  lines.push("# MCP Security Audit Report");
  lines.push("");
  lines.push(`**Target:** \`${result.target}\``);
  lines.push(`**Date:** ${result.startedAt.toISOString()}`);
  lines.push(`**Duration:** ${result.duration}ms`);
  lines.push(`**Scanners:** ${result.scannersRun.join(", ")}`);
  lines.push("");

  // Summary table
  lines.push("## Summary");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  lines.push(`| 🔴 Critical | ${result.summary.critical} |`);
  lines.push(`| 🟠 High | ${result.summary.high} |`);
  lines.push(`| 🟡 Medium | ${result.summary.medium} |`);
  lines.push(`| 🔵 Low | ${result.summary.low} |`);
  lines.push(`| ⚪ Info | ${result.summary.info} |`);
  lines.push(`| **Total** | **${result.summary.total}** |`);
  lines.push("");

  if (result.findings.length === 0) {
    lines.push("> No security findings detected.");
    return lines.join("\n");
  }

  // Findings
  lines.push("## Findings");
  lines.push("");

  for (const finding of result.findings) {
    lines.push(renderFindingMd(finding));
  }

  // Scanner errors
  if (result.scannerErrors.length > 0) {
    lines.push("## Scanner Errors");
    lines.push("");
    for (const err of result.scannerErrors) {
      lines.push(`- **${err.scanner}:** ${err.error}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by [mcp-audit](https://github.com/mcp-audit/mcp-audit)*");

  return lines.join("\n");
}

function renderFindingMd(f: Finding): string {
  const lines: string[] = [];
  const emoji = SEVERITY_EMOJI[f.severity];

  lines.push(`### ${emoji} ${f.title}`);
  lines.push("");
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| ID | \`${f.id}\` |`);
  lines.push(`| Severity | ${f.severity} |`);
  lines.push(`| Scanner | ${f.scanner} |`);
  if (f.target) lines.push(`| Target | \`${f.target}\` |`);
  if (f.cwe) lines.push(`| CWE | ${f.cwe} |`);
  lines.push("");

  lines.push(f.description);
  lines.push("");

  if (f.evidence) {
    lines.push("<details>");
    lines.push("<summary>Evidence</summary>");
    lines.push("");
    if (f.evidence.payload) lines.push(`**Payload:** \`${f.evidence.payload}\``);
    if (f.evidence.request) lines.push(`**Request:** \`${f.evidence.request}\``);
    if (f.evidence.response) {
      lines.push("**Response:**");
      lines.push("```");
      lines.push(f.evidence.response.slice(0, 500));
      lines.push("```");
    }
    if (f.evidence.snippet) {
      lines.push("**Snippet:**");
      lines.push("```");
      lines.push(f.evidence.snippet);
      lines.push("```");
    }
    lines.push("</details>");
    lines.push("");
  }

  if (f.remediation) {
    lines.push(`> **Remediation:** ${f.remediation}`);
    lines.push("");
  }

  return lines.join("\n");
}
